const question = document.querySelector('#question');
const start = document.querySelector('#startResearch');
const status = document.querySelector('#status');
const title = document.querySelector('#runTitle');
const note = document.querySelector('#runNote');
const steps = [...document.querySelectorAll('.steps li')];
const ledger = document.querySelector('#ledger');
const emptyLedger = document.querySelector('#ledgerEmpty');
const brief = document.querySelector('#briefSection');
const toast = document.querySelector('#toast');
let timer;
function notify(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
function resetRun(){clearTimeout(timer);steps.forEach(s=>{s.className='';s.querySelector('.step-state').textContent='—'});status.className='status idle';status.textContent='Idle';title.textContent='Ready when you are';note.textContent='Start a run to see EvidenceFlow work through the question.';ledger.classList.add('hidden');emptyLedger.classList.remove('hidden');brief.classList.add('hidden')}
function runResearch(){const q=question.value.trim();if(!q){question.focus();notify('Add a research question to begin.');return}resetRun();document.querySelector('#projectName').textContent=q.length>30?q.slice(0,30)+'…':q;title.textContent='Researching your question';status.className='status running';status.textContent='Running';note.textContent='Mapping the question into evidence-led research angles…';start.disabled=true;start.textContent='Researching…';let index=0;function advance(){if(index>0){const prev=steps[index-1];prev.className='done';prev.querySelector('.step-state').textContent='✓'}if(index<steps.length){const step=steps[index];step.className='active';step.querySelector('.step-state').textContent='…';note.textContent=['Identifying key terms, stakeholders, and decision criteria…','Reviewing credible sources and capturing supporting passages…','Checking whether sources agree and flagging uncertainty…','Synthesizing findings into a cited decision brief…'][index];index++;timer=setTimeout(advance,850)}else{status.className='status complete';status.textContent='Complete';title.textContent='Research complete';note.textContent='EvidenceFlow reviewed 12 sources and prepared a traceable brief.';emptyLedger.classList.add('hidden');ledger.classList.remove('hidden');brief.classList.remove('hidden');document.querySelector('#briefQuestion').textContent=q;start.disabled=false;start.innerHTML='Start research <span>→</span>';brief.scrollIntoView({behavior:'smooth',block:'start'});}}advance()}
start.addEventListener('click',runResearch);document.querySelector('#newResearch').addEventListener('click',()=>{resetRun();question.value='';question.focus();window.scrollTo({top:0,behavior:'smooth'})});document.querySelectorAll('[data-question]').forEach(button=>button.addEventListener('click',()=>{question.value=button.dataset.question;question.focus()}));document.querySelector('#copyBrief').addEventListener('click',async()=>{const text=document.querySelector('.brief-card').innerText;try{await navigator.clipboard.writeText(text);notify('Brief copied to clipboard.')}catch{notify('Select and copy the brief manually.')}});document.querySelector('#exportBrief').addEventListener('click',()=>window.print());document.querySelector('#shareButton').addEventListener('click',()=>notify('Share link copied to clipboard.'));document.querySelector('#openSources').addEventListener('click',()=>document.querySelector('.findings-panel').scrollIntoView({behavior:'smooth',block:'center'}));document.querySelector('#viewAll').addEventListener('click',()=>notify('All 12 sources will appear in the next version.'));document.querySelectorAll('.citation').forEach(b=>b.addEventListener('click',()=>notify(`Source ${b.dataset.citation} opened in the evidence library.`)));
